# libgda ja.po
# Copyright (C) 1999 Free Software Foundation, Inc.
# Akira TAGOH <tagoh@gnome.gr.jp>, 2000.
#
msgid ""
msgstr ""
"Project-Id-Version: libgda CVS-20010214\n"
"POT-Creation-Date: 2001-02-14 15:42-0500\n"
"PO-Revision-Date: 2001-02-14 15:44-0500\n"
"Last-Translator: Akira TAGOH <tagoh@gnome.gr.jp>\n"
"Language-Team: Japanese <translation@gnome.gr.jp>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=euc-jp\n"
"Content-Transfer-Encoding: 8bit\n"

#: lib/gda-client/gda-connection-pool.c:267
#, c-format
msgid "could not open connection to %s"
msgstr "%s へ接続することが出来ませんでした"

#: lib/gda-client/gda-connection-pool.c:280
#, c-format
msgid "Data source %s not found"
msgstr "データソース %s は見つかりませんでした"

#: lib/gda-client/gda-connection.c:234 lib/gda-client/gda-error.c:179
#, c-format
msgid "%s: The server didn't respond."
msgstr "%s: サーバは応答しませんでした"

#: lib/gda-client/gda-connection.c:238 lib/gda-client/gda-error.c:183
#, c-format
msgid "%s: An Error occured in the CORBA system."
msgstr "%s: CORBA システムでエラーが発生しました"

#: lib/gda-client/gda-connection.c:493
#, c-format
msgid "Database '%s' not found in system configuration"
msgstr "データベース '%s' はシステム設定から見つかりませんでした"

#: lib/gda-client/gda-connection.c:509
msgid "Could not open CORBA factory"
msgstr "CORBA ファクトリを開くことが出来ませんでした"

#: lib/gda-client/gda-field.c:245
msgid "<NULL>"
msgstr "<NULL>"

#: lib/gda-client/gda-field.c:251 lib/gda-client/gda-field.c:253
msgid "<Unknown GDA Type(NULL)>"
msgstr "<未知の GDA タイプ(NULL)>"

#: lib/gda-client/gda-field.c:266
msgid "TRUE"
msgstr "TRUE"

#: lib/gda-client/gda-field.c:267
msgid "FALSE"
msgstr "FALSE"

#: lib/gda-common/gda-corba.c:73
#, c-format
msgid "CORBA System exception: %s"
msgstr "CORBA システム例外: %s"

#: lib/gda-common/gda-corba.c:102
msgid "True"
msgstr "True"

#: lib/gda-common/gda-corba.c:102
msgid "False"
msgstr "False"

#: lib/gda-common/gda-init.c:59
msgid "Attempt to initialize an already initialized client"
msgstr "初期化を試みましたがすでにクライアントは初期化されています"

#: lib/gda-common/gda-log.c:48
msgid "Saving log...x"
msgstr "ログを保存中...x"

#. compose message
#: lib/gda-common/gda-log.c:69
msgid "ERROR: "
msgstr "エラー: "

#: lib/gda-common/gda-log.c:69
msgid "MESSAGE: "
msgstr "メッセージ: "

#: lib/gda-common/gda-thread.c:211
msgid "thread is already running"
msgstr "スレッドはすでに実行中です"

#: lib/gda-common/gda-xml-database.c:282
#, c-format
msgid "table %s already exists"
msgstr "テーブル %s はすでに存在しています"

#: lib/gda-common/gda-xml-database.c:446
#, c-format
msgid "%p is not a valid table"
msgstr "%p は有効なテーブルではありません"

#: lib/gda-server/gda-server-error.c:185
msgid "Could not get pointer to server implementation"
msgstr "サーバの実装へのポインタを取得することが出来ませんでした"

#: lib/gda-server/gda-server-impl-connection.c:123
#: lib/gda-server/gda-server-impl-connection.c:132
#: lib/gda-server/gda-server-impl-connection.c:139
#: lib/gda-server/gda-server-impl-connection.c:148
#: lib/gda-server/gda-server-impl-connection.c:155
#: lib/gda-server/gda-server-impl-connection.c:164
#: lib/gda-server/gda-server-impl-connection.c:171
#: lib/gda-server/gda-server-impl-connection.c:180
#: lib/gda-server/gda-server-impl-recordset.c:126
#: lib/gda-server/gda-server-impl-recordset.c:135
#: lib/gda-server/gda-server-impl-recordset.c:142
#: lib/gda-server/gda-server-impl-recordset.c:157
#: lib/gda-server/gda-server-impl-recordset.c:166
#: lib/gda-server/gda-server-impl-recordset.c:173
#: lib/gda-server/gda-server-impl-recordset.c:182
#: lib/gda-server/gda-server-impl-recordset.c:189
#: lib/gda-server/gda-server-impl-recordset.c:198
#: lib/gda-server/gda-server-impl-recordset.c:205
#: lib/gda-server/gda-server-impl-recordset.c:213
#: lib/gda-server/gda-server-impl-recordset.c:222
#: lib/gda-server/gda-server-impl-recordset.c:229
#: lib/gda-server/gda-server-impl-recordset.c:237
#: lib/gda-server/gda-server-impl-recordset.c:245
#: lib/gda-server/gda-server-impl-recordset.c:273
#: lib/gda-server/gda-server-impl-recordset.c:281
#: lib/gda-server/gda-server-impl-recordset.c:289
#: lib/gda-server/gda-server-impl-recordset.c:297
#: lib/gda-server/gda-server-impl-recordset.c:305
#: lib/gda-server/gda-server-impl-recordset.c:314
#, c-format
msgid "%s not implemented"
msgstr "%s は実装されていません"

#: lib/gda-server/gda-server-impl-connection.c:272
#, c-format
msgid "impl_GDA_Connection_open: opening connection with DSN: %s"
msgstr "impl_GDA_Connection_open: DSN '%s' で接続を開いています"

#: lib/gda-server/gda-server-impl-recordset.c:407
#, c-format
msgid "%s: an error ocurred while fetching data"
msgstr "%s: データ取得中にエラーが発生しました"

#: lib/gda-server/gda-server-impl-recordset.c:446
#, c-format
msgid "%s: length = %d"
msgstr "%s: 長さ = %d"

#: lib/gda-server/gda-server-impl-recordset.c:459
#, c-format
msgid "%s: sending field description for '%s'"
msgstr "%s: '%s' のためのフィールドの記述を送信中"

#: lib/gda-server/gda-server-impl.c:184
#, c-format
msgid "Starting provider %s with no implementation functions"
msgstr "未実装の機能をプロバイダ %s で開始しています"

#: lib/gda-server/gda-server-impl.c:210
#: report/server/gda-report-server-main.c:113
msgid ""
"OAF doesn't know about our IID; indicates broken installation. Exiting..."
msgstr ""
"OAF は IID について知りません; インストールが失敗しているかもれません. "
"終了します..."

#: lib/gda-server/gda-server-impl.c:213
msgid ""
"Another instance of this provider is already registered with OAF. Exiting..."
msgstr ""
"このプロバイダの別のインスタンスはすでに OAF が登録しています. 終了します..."

#: lib/gda-server/gda-server-impl.c:216
msgid "Unknown error registering this provider with OAF. Exiting"
msgstr "OAF がこのプロバイダを登録中に未知のエラーが発生しました. 終了します"

#: lib/gda-server/gda-server-impl.c:220
#, c-format
msgid "Registered with ID = %s"
msgstr "ID = %s で登録しました"

#: lib/gda-server/gda-server-impl.c:296
#, c-format
msgid "CORBA system exception %s"
msgstr "CORBA システム例外 %s"

#: lib/gda-server/gda-server-impl.c:299
#, c-format
msgid "CORBA user exception: %s"
msgstr "CORBA ユーザ例外: %s"

#: lib/gda-server/gda-server-init.c:63 lib/gda-server/gda-server-init.c:69
#, c-format
msgid "Received signal %d, shutting down"
msgstr "シグナル %d を受信しました, 終了します"

#: lib/gda-server/gda-server-init.c:73
#, c-format
msgid "Received signal %d. Ignoring"
msgstr "シグナル %d を受信しました, 無視します"

#: lib/gda-server/gda-server-init.c:123
msgid "Attempt to initialize an already initialized provider"
msgstr "初期化を試みましたがすでにプロバイダは初期化されています"

#: providers/gda-ldap-server/GNOME_GDA_Provider_LDAP.oaf.in.h:1
msgid "GDA Datasource Access for LDAP"
msgstr "LDAP用のGDAデータソースアクセス"

#: providers/gda-interbase-server/gda-interbase-connection.c:261
#: providers/gda-ldap-server/gda-ldap-connection.c:272
#: providers/gda-mdb-server/gda-mdb-connection.c:360
#: providers/gda-mysql-server/gda-mysql-connection.c:387
#: providers/gda-odbc-server/gda-odbc-connection.c:609
#: providers/gda-odbc-server/gda-odbc-connection.c:642
#: providers/gda-oracle-server/gda-oracle-connection.c:426
#: providers/gda-postgres-server/gda-postgres-connection.c:779
#: providers/gda-sybase-server/gda-sybase-error.c:109
#: providers/gda-tds-server/gda-tds-error.c:108
#, c-format
msgid "error '%s' at %s"
msgstr "エラー '%s' が %s で発生しました"

#: providers/gda-interbase-server/gda-interbase-connection.c:266
#: providers/gda-interbase-server/gda-interbase-connection.c:267
#: providers/gda-ldap-server/gda-ldap-connection.c:277
#: providers/gda-ldap-server/gda-ldap-connection.c:278
#: providers/gda-mdb-server/gda-mdb-connection.c:364
#: providers/gda-mdb-server/gda-mdb-connection.c:365
#: providers/gda-mysql-server/gda-mysql-connection.c:391
#: providers/gda-mysql-server/gda-mysql-connection.c:392
#: providers/gda-odbc-server/gda-odbc-connection.c:611
#: providers/gda-odbc-server/gda-odbc-connection.c:612
#: providers/gda-odbc-server/gda-odbc-connection.c:644
#: providers/gda-odbc-server/gda-odbc-connection.c:645
#: providers/gda-oracle-server/gda-oracle-connection.c:431
#: providers/gda-oracle-server/gda-oracle-connection.c:432
#: providers/gda-postgres-server/gda-postgres-connection.c:786
#: providers/gda-postgres-server/gda-postgres-connection.c:787
#: providers/gda-primebase-server/gda-primebase-connection.c:302
#: providers/gda-primebase-server/gda-primebase-connection.c:303
#: providers/gda-sybase-server/gda-sybase-error.c:118
#: providers/gda-sybase-server/gda-sybase-error.c:119
#: providers/gda-tds-server/gda-tds-error.c:117
#: providers/gda-tds-server/gda-tds-error.c:118
msgid "Not available"
msgstr "利用できません"

#: providers/gda-interbase-server/gda-interbase-connection.c:268
#: providers/gda-ldap-server/gda-ldap-connection.c:279
#: providers/gda-mdb-server/gda-mdb-connection.c:366
#: providers/gda-mysql-server/gda-mysql-connection.c:393
#: providers/gda-oracle-server/gda-oracle-connection.c:433
#: providers/gda-postgres-server/gda-postgres-connection.c:788
#: providers/gda-primebase-server/gda-primebase-connection.c:304
#: providers/gda-sybase-server/gda-sybase-error.c:120
#: providers/gda-tds-server/gda-tds-error.c:119
msgid "error"
msgstr "エラー"

#: providers/gda-ldap-server/main-ldap.c:69
msgid "Could not register LDAP provider implementation"
msgstr "LDAP プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-interbase-server/GNOME_GDA_Provider_InterBase.oaf.in.h:1
msgid "GDA Datasource Access for Interbase"
msgstr "Interbase用のGDAデータソースアクセス"

#: providers/gda-interbase-server/gda-interbase-connection.c:260
#, c-format
msgid "Error code %ld"
msgstr "エラーコード %ld"

#: providers/gda-interbase-server/main-interbase.c:70
msgid "Could not register INTERBASE provider implementation"
msgstr "INTERBASE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mail-server/GNOME_GDA_Provider_Mail.oaf.in.h:1
msgid "GDA Datasource Access for Mail"
msgstr "Mail用のGDAデータソースアクセス"

#: providers/gda-mail-server/gda-mail-connection.c:108
#: providers/gda-mdb-server/gda-mdb-connection.c:224
#: providers/gda-mysql-server/gda-mysql-connection.c:251
#: providers/gda-oracle-server/gda-oracle-connection.c:295
#: providers/gda-postgres-server/gda-postgres-connection.c:511
#: providers/gda-sybase-server/gda-sybase-connection.c:269
#: providers/gda-tds-server/gda-tds-connection.c:266
#, c-format
msgid "Unhandled SCHEMA_QTYPE %d"
msgstr "SCHEMA_QTYPE %d は扱えません"

#: providers/gda-mail-server/main-mail.c:70
msgid "Could not register Mail provider implementation"
msgstr "メールプロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mdb-server/GNOME_GDA_Provider_MDB.oaf.in.h:1
msgid "GDA Datasource Access for MDB (MS Access) files"
msgstr "MDB (MS Access)ファイル用のGDAデータソースアクセス"

#. execute command
#: providers/gda-mdb-server/gda-mdb-command.c:86
#: providers/gda-mysql-server/gda-mysql-command.c:87
#: providers/gda-sybase-server/gda-sybase-command.c:120
#: providers/gda-tds-server/gda-tds-command.c:114
#, c-format
msgid "executing command '%s'"
msgstr "コマンド '%s' を実行しています"

#: providers/gda-mdb-server/gda-mdb-command.c:88
#: providers/gda-mysql-server/gda-mysql-command.c:89
#, c-format
msgid "info '%s'"
msgstr "情報 '%s'"

#: providers/gda-mdb-server/gda-mdb-connection.c:137
#: providers/gda-mysql-server/gda-mysql-connection.c:148
#, c-format
msgid ""
"%s:%d: You cannot provide a UNIX_SOCKET if you also provide either a HOST or "
"a PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT "
"options"
msgstr ""
"%s:%d: UNIX_SOCKET を提供することが出来ません. HOST または PORT "
"のどちらかを提供するなら, UNIX_SOCKET を削除するか, HOST と PORT "
"の両方のオプションを削除してください"

#: providers/gda-mdb-server/gda-mdb-connection.c:147
#, c-format
msgid "%s:%d: You must  provide the filename with the MS Access database"
msgstr "%s:%d: MS Access データベースのファイル名を提供しなければなりません"

#: providers/gda-mdb-server/gda-mdb-connection.c:152
#, c-format
msgid "Opening connection with filename=%s, user=%s, password=%s"
msgstr "ファイル名=%s, ユーザ=%s, パスワード=%s で接続を開いています"

#: providers/gda-mdb-server/gda-mdb-connection.c:415
#: providers/gda-mysql-server/gda-mysql-connection.c:442
msgid "mysql_recset is NULL"
msgstr "mysql_recset は NULL です"

#: providers/gda-mdb-server/gda-mdb-connection.c:457
#: providers/gda-mysql-server/gda-mysql-connection.c:484
#: providers/gda-sybase-server/gda-sybase-connection.c:432
#: providers/gda-tds-server/gda-tds-connection.c:423
msgid "No table name given for SCHEMA_COLS"
msgstr "SCHEMA_COLS のためのテーブル名が与えられていません"

#: providers/gda-mdb-server/main-mdb.c:70
#: providers/gda-mysql-server/main-mysql.c:70
msgid "Could not register MySQL provider implementation"
msgstr "MySQL プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-mysql-server/GNOME_GDA_Provider_MySQL.oaf.in.h:1
msgid "GDA Datasource Access for MySQL"
msgstr "MySQL用のGDAデータソースアクセス"

#: providers/gda-mysql-server/gda-mysql-connection.c:162
#, c-format
msgid ""
"Opening connection with user=%s, password=%s, host=%s, port=%s, "
"unix_socket=%s"
msgstr ""
"ユーザ=%s, パスワード=%s, ホスト=%s, ポート=%s, unix ソケット=%s "
"で接続を開いています"

#: providers/gda-odbc-server/GNOME_GDA_Provider_ODBC.oaf.in.h:1
msgid "GDA Datasource Access for ODBC"
msgstr "ODBC用のGDAデータソースアクセス"

#: providers/gda-odbc-server/gda-odbc-connection.c:280
#, c-format
msgid "gda_odbc_connection_open_schema: Unhandled SCHEMA_QTYPE %d\n"
msgstr "gda_odbc_connection_open_schema: SCHEMA_QTYPE %d は扱えません\n"

#: providers/gda-odbc-server/gda-odbc-connection.c:626
#: providers/gda-odbc-server/gda-odbc-connection.c:627
#: providers/gda-odbc-server/gda-odbc-connection.c:628
#: providers/gda-odbc-server/gda-odbc-connection.c:659
#: providers/gda-odbc-server/gda-odbc-connection.c:660
#: providers/gda-odbc-server/gda-odbc-connection.c:661
msgid "no text"
msgstr "テキストがありません"

#: providers/gda-odbc-server/main-odbc.c:69
msgid "Could not register ODBC provider implementation"
msgstr "ODBC プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-oracle-server/GNOME_GDA_Provider_Oracle.oaf.in.h:1
msgid "GDA Datasource Access for Oracle"
msgstr "Oracle用のGDAデータソースアクセス"

#: providers/gda-oracle-server/gda-oracle-command.c:185
msgid "Could not allocate statement handle"
msgstr "ステートメントハンドルを割り当てることが出来ませんでした"

#: providers/gda-oracle-server/gda-oracle-command.c:189
msgid "command object being created without associated connection"
msgstr "コマンドオブジェクトは接続なしで作成しました"

#: providers/gda-oracle-server/gda-oracle-command.c:220
#, c-format
msgid "Executing command '%s'"
msgstr "コマンド '%s' を実行しています"

#: providers/gda-oracle-server/gda-oracle-connection.c:113
msgid "error in OCIHandleAlloc() HTYPE_SVCCTX"
msgstr "OCIHandleAlloc() HTYPE_SVCCTX でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:116
msgid "error in OCIHandleAlloc() HTYPE_SERVER"
msgstr "OCIHandleAlloc() HTYPE_SERVER でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:119
msgid "error in OCIHandleAlloc() HTYPE_ERROR"
msgstr "OCIHandleAlloc() HTYPE_ERROR でエラーが発生しました"

#: providers/gda-oracle-server/gda-oracle-connection.c:379
#, c-format
msgid "Unknown ORACLE type %ld"
msgstr "未知の ORACLE タイプ %ld です"

#: providers/gda-oracle-server/gda-oracle-recordset.c:115
msgid "Unknown ORACLE data type in fill_field_values"
msgstr "fill_field_values に未知の ORACLE データタイプがあります"

#: providers/gda-oracle-server/gda-oracle-recordset.c:150
msgid "recordset object being created without associated connection"
msgstr "レコードセットオブジェクトは接続なしで作成しました"

#: providers/gda-oracle-server/main-oracle.c:69
msgid "Could not register ORACLE provider implementation"
msgstr "ORACLE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-postgres-server/GNOME_GDA_Provider_Postgres.oaf.in.h:1
msgid "GDA Datasource Access for Postgres"
msgstr "Postgres用のGDAデータソースアクセス"

#: providers/gda-postgres-server/gda-postgres-connection.c:888
#: providers/gda-postgres-server/gda-postgres-connection.c:1000
msgid "postgres_recset is NULL"
msgstr "postgres_recset は NULL です"

#: providers/gda-postgres-server/main-postgres.c:69
msgid "Could not register PostgreSQL provider implementation"
msgstr "PostgreSQL プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-sybase-server/GNOME_GDA_Provider_Sybase.oaf.in.h:1
msgid "GDA Datasource Access for Sybase"
msgstr "Sybase用のGDAデータソースアクセス"

#: providers/gda-sybase-server/gda-sybase-command.c:115
#: providers/gda-tds-server/gda-tds-command.c:110
msgid "Connection seems to be dead"
msgstr "接続は切れたようです"

#: providers/gda-sybase-server/gda-sybase-command.c:135
#: providers/gda-tds-server/gda-tds-command.c:125
msgid "Filling command structure failed\n"
msgstr "コマンド構造体の充填に失敗しました\n"

#: providers/gda-sybase-server/gda-sybase-command.c:147
#: providers/gda-tds-server/gda-tds-command.c:133
msgid "sending cmd failed"
msgstr "コマンドの送信に失敗しました"

#: providers/gda-primebase-server/gda-primebase-command.c:110
#: providers/gda-sybase-server/gda-sybase-command.c:154
#: providers/gda-tds-server/gda-tds-command.c:140
msgid "Allocating recordset failed"
msgstr "レコードセットの割り当てに失敗しました"

#: providers/gda-primebase-server/gda-primebase-command.c:117
#: providers/gda-sybase-server/gda-sybase-command.c:164
#: providers/gda-tds-server/gda-tds-command.c:148
msgid "Getting recordset userdata failed"
msgstr "レコードセットのユーザデータの取得に失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:222
#: providers/gda-tds-server/gda-tds-command.c:201
msgid "Command execution finished, all results processed"
msgstr "コマンドの実行は完了しました, すべての結果を処理しました"

#: providers/gda-sybase-server/gda-sybase-command.c:226
#: providers/gda-tds-server/gda-tds-command.c:205
msgid "Command failed"
msgstr "コマンドは失敗しました"

#: providers/gda-sybase-server/gda-sybase-command.c:230
#: providers/gda-tds-server/gda-tds-command.c:209
msgid "Execution of resultless command succeeded"
msgstr "結果のない実行コマンドは成功しました"

#: providers/gda-sybase-server/gda-sybase-command.c:246
#: providers/gda-tds-server/gda-tds-command.c:225
#, c-format
msgid "ct_results() returned %x"
msgstr "ct_results() は %x を返しました"

#: providers/gda-sybase-server/gda-sybase-command.c:256
#: providers/gda-tds-server/gda-tds-command.c:235
msgid "No further results, command completly succeeded."
msgstr "深刻な結果はありません, コマンドは完全に成功しました"

#: providers/gda-sybase-server/gda-sybase-command.c:260
#: providers/gda-tds-server/gda-tds-command.c:239
msgid "An error occured during command execution."
msgstr "コマンド実行中にエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-command.c:267
#: providers/gda-tds-server/gda-tds-command.c:243
msgid "Cmd execution returned unknown result, may be an error"
msgstr "コマンド実行は未知の結果を返しました, エラーかもしれません"

#: providers/gda-sybase-server/gda-sybase-command.c:280
#: providers/gda-tds-server/gda-tds-command.c:253
msgid "No data returned, freeing recordset structure"
msgstr "データが返されません, レコードセット構造体を開放しています"

#: providers/gda-sybase-server/gda-sybase-command.c:311
#: providers/gda-sybase-server/gda-sybase-command.c:323
#: providers/gda-tds-server/gda-tds-command.c:283
#: providers/gda-tds-server/gda-tds-command.c:291
msgid "Freeing command structure failed"
msgstr "コマンド構造体の開放に失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:149
#: providers/gda-tds-server/gda-tds-connection.c:137
msgid "Error allocating error structure"
msgstr "エラー構造体の割当て中にエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:157
msgid "Not enough memory for sybase_Connection"
msgstr "sybase_Connection のための十分なメモリがありません"

#: providers/gda-sybase-server/gda-sybase-connection.c:422
#: providers/gda-tds-server/gda-tds-connection.c:413
#, c-format
msgid "schema_cols: table_name '%s'"
msgstr "schema_cols: table_name '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:438
#: providers/gda-tds-server/gda-tds-connection.c:429
msgid "Could not allocate command structure"
msgstr "コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:460
#: providers/gda-tds-server/gda-tds-connection.c:451
msgid "Could not allocate enough memory for query"
msgstr "クエリのための十分なメモリを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:474
#: providers/gda-tds-server/gda-tds-connection.c:465
msgid "Could not get recordset in schema_cols"
msgstr "schema_cols からレコードセットを取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:506
#: providers/gda-sybase-server/gda-sybase-connection.c:583
#: providers/gda-tds-server/gda-tds-connection.c:497
#: providers/gda-tds-server/gda-tds-connection.c:574
#, c-format
msgid "schema_tables: table name = '%s'"
msgstr "schema_tables: テーブル名 = '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:514
#: providers/gda-sybase-server/gda-sybase-connection.c:591
#: providers/gda-tds-server/gda-tds-connection.c:505
#: providers/gda-tds-server/gda-tds-connection.c:582
#, c-format
msgid "schema_tables: table_schema = '%s'"
msgstr "schema_tables: table_schema = '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:519
#: providers/gda-tds-server/gda-tds-connection.c:510
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!\n"
msgstr "schema_procedures: proc_catalog = %s' は使っていません!\n"

#: providers/gda-sybase-server/gda-sybase-connection.c:523
#: providers/gda-tds-server/gda-tds-connection.c:514
#, c-format
msgid "schema_procs: invalid constraint type %d"
msgstr "schema_procs: 制約タイプ %d は無効です"

#: providers/gda-sybase-server/gda-sybase-connection.c:533
#: providers/gda-tds-server/gda-tds-connection.c:524
msgid "Could not allocate cmd structure"
msgstr "コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:596
#: providers/gda-tds-server/gda-tds-connection.c:587
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!"
msgstr "schema_procedures: proc_catalog = '%s' は使っていません!"

#: providers/gda-sybase-server/gda-sybase-connection.c:600
#: providers/gda-tds-server/gda-tds-connection.c:591
#, c-format
msgid "schema_tables: invalid constraint type %d"
msgstr "schema_tables: 制約タイプ %d は無効です"

#: providers/gda-sybase-server/gda-sybase-connection.c:661
#: providers/gda-tds-server/gda-tds-connection.c:652
#, c-format
msgid "Invalid or unsupported constraint type: %d"
msgstr "制約タイプは無効またはサポートしていません: %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:702
#: providers/gda-tds-server/gda-tds-connection.c:693
msgid "Could not allocate Gda_ServerCommand"
msgstr "Gda_ServerCommand の割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:732
#: providers/gda-sybase-server/gda-sybase-connection.c:737
#: providers/gda-tds-server/gda-tds-connection.c:723
#: providers/gda-tds-server/gda-tds-connection.c:728
#, c-format
msgid "connection status: %x"
msgstr "接続状況: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:733
#: providers/gda-tds-server/gda-tds-connection.c:724
#, c-format
msgid "return code: %x"
msgstr "戻り値: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:770
#: providers/gda-tds-server/gda-tds-connection.c:759
msgid "attempting reconnection"
msgstr "再接続を試みています"

#: providers/gda-sybase-server/gda-sybase-connection.c:909
#, c-format
msgid "Reconnected to '%s'"
msgstr "'%s' へ再接続しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:911
#: providers/gda-tds-server/gda-tds-connection.c:864
#, c-format
msgid "Connected to %s"
msgstr "%s に接続完了"

#: providers/gda-sybase-server/gda-sybase-connection.c:919
#: providers/gda-tds-server/gda-tds-connection.c:874
#, c-format
msgid "Selected database '%s'"
msgstr "データベース '%s' を選択しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:948
#: providers/gda-tds-server/gda-tds-connection.c:899
#, c-format
msgid "%s: Could not allocate cmd structure"
msgstr "%s: コマンド構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:957
#: providers/gda-tds-server/gda-tds-connection.c:908
#, c-format
msgid "%s: Could not allocate memory for cmd string"
msgstr "%s: コマンド文字列のためのメモリを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:970
#: providers/gda-tds-server/gda-tds-connection.c:918
#, c-format
msgid "%s: ct_command failed"
msgstr "%s: ct_command は失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:979
#: providers/gda-tds-server/gda-tds-connection.c:927
#, c-format
msgid "%s: sending command failed"
msgstr "%s: コマンドの送信は失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:990
#, c-format
msgid "%s: selecting database failed"
msgstr "%s: データベースの選択に失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:1008
#, c-format
msgid "%s: use command failed"
msgstr "%s: ユーザコマンドは失敗しました"

#: providers/gda-sybase-server/gda-sybase-connection.c:1035
#: providers/gda-tds-server/gda-tds-connection.c:989
msgid "Could not allocate locale structure"
msgstr "ロケール構造体を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1041
#: providers/gda-tds-server/gda-tds-connection.c:995
#, c-format
msgid "Could not set locale to '%s'"
msgstr "'%s' にロケールを設定することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1047
#: providers/gda-tds-server/gda-tds-connection.c:1001
#, c-format
msgid "Could not configure locale to be '%s'"
msgstr "'%s' にロケールを設定することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1052
#: providers/gda-tds-server/gda-tds-connection.c:1006
msgid "Could not drop locale structure"
msgstr "ロケール構造体をドロップすることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-connection.c:1065
#: providers/gda-tds-server/gda-tds-connection.c:1019
#, c-format
msgid "Fatal error: %s\n"
msgstr "致命的なエラー: %s\n"

#: providers/gda-sybase-server/gda-sybase-error.c:65
#, c-format
msgid "gda_sybase_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-sybase-server/gda-sybase-error.c:74
#: providers/gda-tds-server/gda-tds-error.c:72
#, c-format
msgid "No error flag ist set, though %s is called. This may be a bug."
msgstr ""
"%s が呼ばれたにもかかわらずエラーフラグが設定されていません. "
"これは不具合かもしれません"

#: providers/gda-sybase-server/gda-sybase-error.c:138
msgid "cs_diag() initialized"
msgstr "cs_diag() を初期化しました"

#: providers/gda-sybase-server/gda-sybase-error.c:141
msgid "Could not initialize cs_diag()"
msgstr "cs_diag() を初期化することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:148
msgid "ct_diag() initialized"
msgstr "ct_diag() を初期化しました"

#: providers/gda-sybase-server/gda-sybase-error.c:151
msgid "Could not initialize ct_diag()"
msgstr "ct_diag() を初期化することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:185
#, c-format
msgid "%s could not find server implementation"
msgstr "%s をサーバの実装から見付けることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:191
#, c-format
msgid "%s could not get cnc userdata"
msgstr "%s は cnc ユーザデータを取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:203
msgid "Could not get # of messages"
msgstr "メッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:208
#, c-format
msgid "%d ctlib messages to fetch"
msgstr "%d 個の ctlib メッセージを取得しました"

#: providers/gda-sybase-server/gda-sybase-error.c:210
#, c-format
msgid "%d ctlib message to fetch"
msgstr "%d 個の ctlib メッセージを取得しました"

#: providers/gda-sybase-server/gda-sybase-error.c:246
msgid "error is nullpointer in gda_sybase_messages_handle"
msgstr "gda_sybase_messages_handle の NULL ポインタはエラーです"

#: providers/gda-sybase-server/gda-sybase-error.c:271
#: providers/gda-sybase-server/gda-sybase-error.c:338
#: providers/gda-sybase-server/gda-sybase-error.c:381
msgid "Could not get # of server messages"
msgstr "サーバメッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:279
#, c-format
msgid "Fetching %d client messages"
msgstr "%d 個のクライアントメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:281
#, c-format
msgid "Fetching %d client message"
msgstr "%d 個のクライアントメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:290
#, c-format
msgid "Could not get client msg # %d"
msgstr "クライアントメッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:306
msgid "Could not get # of client messages"
msgstr "クライアントメッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:314
msgid "Could not clear client messages"
msgstr "クライアントメッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:346
#, c-format
msgid "Fetching %d server messages"
msgstr "%d 個のサーバメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:348
#, c-format
msgid "Fetching %d server message"
msgstr "%d 個のサーバメッセージを取得しています"

#: providers/gda-sybase-server/gda-sybase-error.c:357
#, c-format
msgid "Could not get server msg # %d"
msgstr "サーバメッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:389
msgid "Could not clear server messages"
msgstr "サーバメッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:411
#: providers/gda-sybase-server/gda-sybase-error.c:447
msgid "Could not get # of cslib messages"
msgstr "cslib メッセージ数を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:419
#, c-format
msgid "Fetching %d cslib messages"
msgstr "%d 個の cslib メッセージを取得してします"

#: providers/gda-sybase-server/gda-sybase-error.c:421
#, c-format
msgid "Fetching %d cslib message"
msgstr "%d 個の cslib メッセージを取得してします"

#: providers/gda-sybase-server/gda-sybase-error.c:431
#, c-format
msgid "Could not get cslib msg # %d"
msgstr "cslib メッセージ番号 %d を取得することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:455
msgid "Could not clear cslib messages"
msgstr "cslib メッセージを消去することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-error.c:587
#: providers/gda-tds-server/gda-tds-error.c:251
msgid "Server message:"
msgstr "サーバメッセージ:"

#: providers/gda-sybase-server/gda-sybase-error.c:596
#: providers/gda-tds-server/gda-tds-error.c:260
msgid "Client message:"
msgstr "クライアントメッセージ:"

#: providers/gda-sybase-server/gda-sybase-error.c:603
#: providers/gda-tds-server/gda-tds-error.c:267
msgid "CS-Library error:"
msgstr "CS-Library エラー:"

#: providers/gda-sybase-server/gda-sybase-recordset.c:152
#: providers/gda-tds-server/gda-tds-recordset.c:149
#, c-format
msgid "fetch error at row %d"
msgstr "%d 列目の取得でエラーが発生しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:159
#: providers/gda-tds-server/gda-tds-recordset.c:156
#, c-format
msgid "CS_END_DATA on row %d; canceling"
msgstr "%d 列目で CS_END_DATA; キャンセル中"

#: providers/gda-sybase-server/gda-sybase-recordset.c:168
#: providers/gda-tds-server/gda-tds-recordset.c:163
#, c-format
msgid "%s: Error (%d)"
msgstr "%s: エラー (%d)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:343
#: providers/gda-tds-server/gda-tds-recordset.c:336
msgid "Failed fetching # of columns"
msgstr "カラム数の取得に失敗しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:349
#: providers/gda-tds-server/gda-tds-recordset.c:343
#, c-format
msgid "Counted %d columns"
msgstr "%d カラムをカウントしました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:356
#: providers/gda-tds-server/gda-tds-recordset.c:350
#, c-format
msgid "%s could not allocate datafmt info"
msgstr "%s はデータフォーマット情報を割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:366
#: providers/gda-tds-server/gda-tds-recordset.c:360
#, c-format
msgid "%s could not allocate data fields"
msgstr "%s はデータフィールドを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:384
#: providers/gda-tds-server/gda-tds-recordset.c:378
#, c-format
msgid "ct_describe on col # %d"
msgstr "カラム番号 %d で ct_describe します"

#: providers/gda-sybase-server/gda-sybase-recordset.c:391
#: providers/gda-tds-server/gda-tds-recordset.c:385
#, c-format
msgid "ct_describe on col # %d failed"
msgstr "カラム番号 %d で ct_describe に失敗しました"

#: providers/gda-sybase-server/gda-sybase-recordset.c:397
#: providers/gda-tds-server/gda-tds-recordset.c:391
#, c-format
msgid "ct_describe(%d): '%s', %d (%s)"
msgstr "ct_describe(%d): '%s', %d (%s)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:406
#: providers/gda-tds-server/gda-tds-recordset.c:400
msgid "could not allocate data holder"
msgstr "データホルダーを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:416
#: providers/gda-tds-server/gda-tds-recordset.c:410
msgid "could not ct_bind data holder to column"
msgstr "カラムにデータホルダーを ct_bind することが出来ませんでした"

#: providers/gda-sybase-server/gda-sybase-recordset.c:423
#: providers/gda-tds-server/gda-tds-recordset.c:417
msgid "illegal type detected, aborting"
msgstr "不当なタイプを検出しました, 中止しています"

#: providers/gda-sybase-server/gda-sybase-recordset.c:429
#: providers/gda-tds-server/gda-tds-recordset.c:423
msgid "could not allocate field"
msgstr "フィールドを割り当てることが出来ませんでした"

#: providers/gda-sybase-server/main-sybase.c:74
msgid "Could not register gda-sybase provider implementation"
msgstr "gda-sybase プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-primebase-server/GNOME_GDA_Provider_Primebase.oaf.in.h:1
msgid "GDA Datasource Access for primebase"
msgstr "primebase用のGDAデータソースアクセス"

#: providers/gda-primebase-server/gda-primebase-command.c:128
msgid "An error occured."
msgstr "エラーが発生しました"

#: providers/gda-primebase-server/gda-primebase-connection.c:137
#, c-format
msgid "%2ld: Connected to '%s@%s' with connparm: '%s'"
msgstr "%2ld: '%s@%s'へ接続パラメータ '%s'で接続しました"

#: providers/gda-primebase-server/gda-primebase-connection.c:142
#, c-format
msgid "%2ld: ConInfo: %s@%s, Client API v%x, status: %x"
msgstr "%2ld: 接続情報: %s@%s, クライアントAPI v%x, ステータス: %x"

#: providers/gda-primebase-server/gda-primebase-connection.c:145
#, c-format
msgid "Could not connect to '%s'"
msgstr "%s へ接続することが出来ませんでした"

#: providers/gda-primebase-server/gda-primebase-connection.c:316
msgid "Not enough memory for primebase_Error structure."
msgstr "primebase_Error 構造体のための十分なメモリがありません"

#: providers/gda-primebase-server/gda-primebase-connection.c:324
#, c-format
msgid "%2ld: ERROR: %ld (%ld) : %s.\n"
msgstr "%2ld: エラー: %ld (%ld) : %s.\n"

#: providers/gda-primebase-server/gda-primebase-recordset.c:190
msgid "No according field found"
msgstr "一致するフィールドが見つかりません"

#: providers/gda-primebase-server/main-primebase.c:68
msgid "Could not register PRIMEBASE provider implementation"
msgstr "PRIMEBASE プロバイダの実装を登録することが出来ませんでした"

#: providers/gda-tds-server/GNOME_GDA_Provider_TDS.oaf.in.h:1
msgid "GDA Datasource Access for Sybase/MS SQL"
msgstr "Sybase/MS SQL用のGDAデータソースアクセス"

#: providers/gda-tds-server/gda-tds-connection.c:145
msgid "Not enough memory for tds_Connection"
msgstr "tds_Connection のための十分なメモリがありません"

#: providers/gda-tds-server/gda-tds-connection.c:862
#, c-format
msgid "Reconnected to %s"
msgstr "'%s' へ再接続しました"

#: providers/gda-tds-server/gda-tds-error.c:63
#, c-format
msgid "gda_tds_error_make(%p,%p,%p,%p)"
msgstr "gda_tds_error_make(%p,%p,%p,%p)"

#: providers/gda-tds-server/main-tds.c:74
msgid "Could not register gda-tds provider implementation"
msgstr "gda-tds プロバイダの実装を登録することが出来ませんでした"

#: report/gda-report-engine.c:209
#, c-format
msgid "CORBA exception unloading report engine: %s"
msgstr "CORBA 例外はレポートエンジンを取り外しています: %s"

#: report/server/GNOME_GDA_Report.oaf.in.h:1
msgid "GDA Distributed Report Engine"
msgstr "GDA分配レポートエンジン"

#: report/server/gda-report-server-main.c:41
#: report/server/gda-report-server-main.c:48
#, c-format
msgid "Received signal %d, shutting down."
msgstr "シグナル %d を受信しました, 終了します"

#: report/server/gda-report-server-main.c:52
#, c-format
msgid "Received signal %d, shutting down cleanly"
msgstr "シグナル %d を受信しました, きれいに終了します"

#: report/server/gda-report-server-main.c:92
msgid "Failed to initialize OAF: please mail bug report to OAF maintainers"
msgstr "OAF の初期化に失敗: OAF メンテナへ不具合報告をメールしてください"

#: report/server/gda-report-server-main.c:101
msgid "Could not activate report engine"
msgstr "レポートエンジンを始動させることが出来ませんでした"

#: report/server/gda-report-server-main.c:116
msgid ""
"Another instance of the report engine is already registered with OAF. "
"Exiting..."
msgstr ""
"レポートエンジンの別のインスタンスはすでに OAF が登録しています. "
"終了します..."

#: report/server/gda-report-server-main.c:119
msgid "Unknown error registering report engine with OAF. Exiting"
msgstr "OAF がレポートエンジンを登録中に未知のエラーが発生しました. 終了します"

#: report/server/gda-report-server-main.c:123
#, c-format
msgid "Registered report engine with ID = %s"
msgstr "ID = %s でレポートエンジンを登録しました"

#: tools/gda-run.c:34
msgid "database name"
msgstr "データベース名"

#: tools/gda-run.c:34
msgid "DATABASE"
msgstr "DATABASE"

#: tools/gda-run.c:35
msgid "user name"
msgstr "ユーザ名"

#: tools/gda-run.c:35
msgid "USER-NAME"
msgstr "USER-NAME"

#: tools/gda-run.c:36
msgid "password"
msgstr "パスワード"

#: tools/gda-run.c:36
msgid "PASSWORD"
msgstr "PASSWORD"

#: tools/gda-run.c:37
msgid "file name"
msgstr "ファイル名"

#: tools/gda-run.c:37
msgid "FILE-NAME"
msgstr "FILE-NAME"

#: tools/gda-run.c:109
#, c-format
msgid "%s: misconfigured DSN entry"
msgstr "%s: DSN エントリの設定ミスです"

#: tools/gda-run.c:124
#, c-format
msgid "%s: data source '%s' not found\n"
msgstr "%s: データソース '%s' は見つかりませんでした\n"
